---
language: ruby
sudo: false
cache: bundler
script: "bundle exec rake ci"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx-2
  - jruby-19mode
matrix:
  include:
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
notifications:
  email: false
